Ejercicio 1

In [1]:
import numpy as np
import networkx as nx
import scipy.linalg as la

Defaulting to user installation because normal site-packages is not writeable


In [ ]:
def leer_archivo(input_file_path):

    f = open(input_file_path, 'r')
    n = int(f.readline())
    m = int(f.readline())
    W = np.zeros(shape=(n,n))
    for _ in range(m):
    	line = f.readline()
    	i = int(line.split()[0]) - 1
    	j = int(line.split()[1]) - 1
    	W[j,i] = 1.0
    f.close()

    return W

In [ ]:
leer_archivo("mathworld_grafo.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'mathworld_grafo.txt'

In [ ]:
def dibujarGrafo(W, print_ejes=True):

    options = {
    'node_color': 'yellow',
    'node_size': 200,
    'width': 3,
    'arrowstyle': '-|>',
    'arrowsize': 10,
    'with_labels' : True}

    N = W.shape[0]
    G = nx.DiGraph(W.T)

    #renombro nodos de 1 a N
    G = nx.relabel_nodes(G, {i:i+1 for i in range(N)})
    if print_ejes:
        print('Ejes: ', [e for e in G.edges])

    nx.draw(G, pos=nx.spring_layout(G), **options)



In [ ]:
dibujarGrafo(leer_archivo("test_aleatorio.txt"))

FileNotFoundError: [Errno 2] No such file or directory: 'test_aleatorio.txt'

In [ ]:
leer_archivo("test_aleatorio.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'test_aleatorio.txt'

In [ ]:

dibujarGrafo(leer_archivo("test_aleatorio.txt"))

FileNotFoundError: [Errno 2] No such file or directory: 'test_aleatorio.txt'

In [ ]:
def calcularRanking(M, p):
    npages = M.shape[0]
    rnk = np.arange(0, npages) # ind{k] = i, la pagina k tienen el iesimo orden en la lista.
    scr = np.zeros(npages) # scr[k] = alpha, la pagina k tiene un score de alpha
    #Codigo
    grado=vectorGrado(M)

    matrizA = matrizA(M, grado, p)



    return rnk, scr

def obtenerMaximoRankingScore(M, p):
    output = -np.inf
    # calculo el ranking y los scores
    rnk, scr = calcularRanking(M, p)
    output = np.max(scr)

    return output

In [ ]:
def vectorGrado(M):
    vectorGrado=np.zeros(shape=(len(M)))
    for m in range(0,len(M),1): # columna m
       for n in range(0,len(M),1): #fila n
           if M[n][m]==1:
              vectorGrado[m]=vectorGrado[m]+1
    return vectorGrado

def matrizPuntajes(M, C):
  matrizPuntajes = np.zeros([len(M), len(M)])
  for m in range(0,len(M),1): # columna m
       for n in range(0,len(M),1): #fila n
          if M[n][m]==1:
            if C[m] != 0:
              matrizPuntajes[n][m] = 1/C[m]
  return matrizPuntajes

def matrizA(M, C, P):
  matrizA = np.zeros([len(M), len(M)])
  for m in range(0,len(M),1): # columna m
       for n in range(0,len(M),1): #fila n
          if C[m] != 0:
            matrizA[n][m] = (1-P)/len(M)+(P * M[n][m])/C[m]
          else:
            matrizA[n][m] = 1/len(M)
  return matrizA


In [ ]:
vectorGrado(leer_archivo("mathworld_grafo.txt"))

array([3., 0., 2., 5., 4., 5., 4., 4., 4., 0.])

In [ ]:
path = "test_aleatorio.txt"
probabilidad = 0.7
archivo = leer_archivo(path)
#archivo = [[3, 6, 0],[-4, -2, 7],[8, 2, 2]]

print(archivo)
print()
print(vectorGrado(archivo))
print()
print(matrizPuntajes(archivo, vectorGrado(archivo)))
print()
print(matrizA(archivo, vectorGrado(archivo), probabilidad))

L, U, P, a = resolver_PA_LU(matrizA(archivo, vectorGrado(archivo), probabilidad))

print("PmatrizA")
print(P @ matrizA(archivo, vectorGrado(archivo), probabilidad))
print()
print("LU")
print(L @ U)

print()

FileNotFoundError: [Errno 2] No such file or directory: 'test_aleatorio.txt'

In [ ]:
path = "test_dosestrellas.txt"
probabilidad = 0.3

n = 7
if path != "":
  B = matrizA(leer_archivo(path),vectorGrado(leer_archivo(path)), probabilidad)
else:
  B = np.eye(n) - np.tril(np.ones((n,n)),-1)
  B[:n,n-1] = 1
print('Matriz B \n', B)

L,U,P,cant_oper = resolver_PA_LU(B)

print('Matriz L \n', L)
print('Matriz U \n', U)
print('Cantidad de operaciones: ', cant_oper)
print('PB=LU? ' , 'Si!' if np.allclose(np.linalg.norm(B - L @ U, 1), 0) else 'No!')
print(P @ B - L @ U)
print('Norma infinito de U: ', np.max(np.sum(np.abs(U), axis=1)) )

Matriz B 
 [[0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.11833333
  0.05833333 0.20833333 0.05833333 0.05833333 0.05833333 0.05833333]
 [0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.11833333
  0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.05833333]
 [0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.11833333
  0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.05833333]
 [0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.11833333
  0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.05833333]
 [0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.11833333
  0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.05833333]
 [0.20833333 0.35833333 0.35833333 0.35833333 0.35833333 0.05833333
  0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.05833333]
 [0.05833333 0.05833333 0.05833333 0.05833333 0.05833333 0.05833333
  0.05833333 0.20833333 0.35833333 0.35833333 0.35833333 0.35833333]
 [0.20833333 0.05833333 0.0583

In [ ]:
def resolver_PA_LU(A): #matriz A de nxm
  U = A
  L = np.identity(len(A)).transpose()
  Permutacion = np.identity(len(A))

  #Calculo de permutacion
  for m in range (0, len(A)-1):
    P = np.identity(len(A))
    max_col = np.absolute(U[m][m])
    pos_fila = m

    for n in range(m, len(A)):
      if np.absolute(U[n][m]) > max_col:
        max_col = np.absolute(U[n][m])
        pos_fila = n

    #puedo calcular mi P que son las permutaciones que se van realizando
    P[[m,pos_fila]] = P[[pos_fila,m]] #intercambia fila en una matriz
    Permutacion = P @ Permutacion

    #Matriz Permutada
    U = P @ U

    #Chequeo si ya esta tringulado la columna
    if(max_col != 0):
      #Calculo de T=Triangulacion
      T = np.identity(len(A))
      for n in range(m+1, len(A)):
        T[n][m] = -1 * (U[n][m]/U[m][m])
        L[m][n] = -1 * (U[n][m]/U[m][m])

      print(L)
      #Calculo por columna de L
      for n in range(0, m+1):
        L[m] = P @ L[m]

      #Calculo U
      U = T @ U

  L=np.linalg.inv(L.transpose()) #esta matriz siempre va a ser inversible por ser una matriz inferior

  return L, U, Permutacion, 6

In [ ]:

def resolver_PA_LU(A): #matriz A de nxm
  U = A
  L = np.identity(len(A))
  Permutacion = np.identity(len(A))

  #Calculo de permutacion
  for m in range (0, len(A)-1):
    P = np.identity(len(A))
    max_col = np.absolute(U[m][m])
    pos_fila = m

    for n in range(m, len(A)):
      if np.absolute(U[n][m]) > max_col:
        max_col = np.absolute(U[n][m])
        pos_fila = n

    #puedo calcular mi P que son las permutaciones que se van realizando
    P[[m,pos_fila]] = P[[pos_fila,m]] #intercambia fila en una matriz
    Permutacion = P @ Permutacion

    #Matriz Permutada
    U = P @ U
    L = P @ L

    #Calculo de T=Triangulacion
    T = np.identity(len(A))
    for n in range(m+1, len(A)):
      T[n][m] = -1 * (U[n][m]/U[m][m])

    #Calculo L
    L = T @ L
    #Calculo U
    U = T @ U

  L=np.linalg.inv(L) #esta matris siempre va a ser inversible por ser una matriz inferior


  print("RESULTADOS")
  print("Matriz L")
  print(L)

  print("Matriz U")
  print(U)

  print("Matriz P")
  print(Permutacion)

  #print(Permutacion @ A)
  #print("=")
  #print(L @ U)

  #Calculo de P final
  print()
  print(P @ A)
  print()
  print(L @ U)

resolver_PA_LU([[3, 6, 0],[-4, -2, 7],[8, 2, 2]])



RESULTADOS
Matriz L
[[ 0.375       1.          0.        ]
 [-0.5        -0.19047619  1.        ]
 [ 1.          0.          0.        ]]
Matriz U
[[ 8.          2.          2.        ]
 [ 0.          5.25       -0.75      ]
 [ 0.          0.          7.85714286]]
Matriz P
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

[[ 3.  6.  0.]
 [ 8.  2.  2.]
 [-4. -2.  7.]]

[[ 3.  6.  0.]
 [-4. -2.  7.]
 [ 8.  2.  2.]]


Prueba de LU

In [ ]:
def pivoteo_partial(A):
    P = np.identity(len(A))
    for j in range(0,len(A)): #recorre columna
        max_col = 0
        pos_fila_max = j #indice de la columna actual
        for i in range(j, len(A)): #recorre fila
            if np.abs(A[i][j]) > max_col:
                max_col = np.abs(A[i][j])
                pos_fila_max = i

        P[[j, pos_fila_max]] = P[[pos_fila_max,j]]
        A = P @ A
    return P

A=[[1, -8, 1],[-4, -2, 1],[1, -4, 1]]
pivoteo_partial(A)


array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [ ]:
def resolver_PA_LU(A):
    U = np.copy(A)
    T= np.identity(len(A))
    L= np.identity(len(A))

    for j in range (0, len(A)-1):
        P = pivoteo_partial(A)
        U = P @ U
        for i in range(j, len(A)):
          T[i][j] = -1 * (U[i][j]/U[j][j])

        U = T @ U
        L = T @ L

    return U,L

A=[[1, -8, 1],[-4, -2, 1],[1, -4, 1]]
U,L=resolver_PA_LU(A)


print("Matriz L")
print(L)

print("Matriz U")
print(U)

NameError: name 'pivoteo_partial' is not defined