# Segunda parte del TP de ALC 2025

In [1]:
# Carga de paquetes necesarios para graficar
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd # Para leer archivos
import geopandas as gpd # Para hacer cosas geográficas
import seaborn as sns # Para hacer plots lindos
import networkx as nx # Construcción de la red en NetworkX
import scipy

##### Carga de funciones del Template

In [2]:
# Importamos las funciones del template
from template_funciones_2 import *

In [3]:
s = (1,1,1,-8,-2,2,-2,2)

vector_s(s)

array([ 1.,  1.,  1., -1., -1.,  1., -1.,  1.])

# Pruebas con la matriz base

In [4]:
# Matriz A de ejemplo
A_ejemplo = np.array([
    [0, 1, 1, 1, 0, 0, 0, 0],
    [1, 0, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 1],
    [0, 0, 1, 0, 1, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 0, 1],
    [0, 0, 0, 0, 1, 1, 1, 0]
])

A_ejemplo

array([[0, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0]])

In [5]:
calcular_matriz_K(A_ejemplo)

array([[3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 3.]])

In [6]:
np.linalg.eigvals(A_ejemplo)[np.argsort(np.abs(np.linalg.eigvals(A_ejemplo)))]

array([ 2.05561087e-17, -5.61552813e-01, -1.00000000e+00, -1.00000000e+00,
       -1.56155281e+00, -2.00000000e+00,  2.56155281e+00,  3.56155281e+00])

In [7]:
np.linalg.eig(A_ejemplo)[1][np.argsort(np.abs(np.linalg.eigvals(A_ejemplo)))]

array([[-3.07706105e-01,  3.94102719e-01, -3.07706105e-01,
         8.26507924e-17,  3.94102719e-01, -3.44500665e-16,
         2.91167878e-17, -7.06603681e-01],
       [-3.94102719e-01,  3.07706105e-01,  3.94102719e-01,
        -1.35752217e-16, -3.07706105e-01, -5.00000000e-01,
         5.00000000e-01,  2.43540988e-18],
       [-3.94102719e-01, -3.07706105e-01, -3.94102719e-01,
        -1.00809392e-16, -3.07706105e-01,  5.00000000e-01,
         5.00000000e-01,  2.32474286e-16],
       [-3.07706105e-01,  3.94102719e-01, -3.07706105e-01,
         8.26507924e-17,  3.94102719e-01, -3.26989267e-16,
         1.38749368e-16,  7.06603681e-01],
       [-3.94102719e-01, -3.07706105e-01, -3.94102719e-01,
         8.82754672e-17, -3.07706105e-01, -5.00000000e-01,
        -5.00000000e-01, -1.54176994e-16],
       [-3.94102719e-01,  3.07706105e-01,  3.94102719e-01,
        -2.99340848e-17, -3.07706105e-01,  5.00000000e-01,
        -5.00000000e-01, -3.17167278e-17],
       [-3.07706105e-01, -3.941027

In [8]:
metpot1(A_ejemplo)

(array([-0.30763801, -0.30763801, -0.39404957, -0.39404953, -0.3941559 ,
        -0.39415586, -0.30777419, -0.30777419]),
 3.561552782954885,
 True)

In [9]:
deflaciona(A_ejemplo)

array([[-0.3370943 ,  0.6629057 ,  0.56822648,  0.56822649, -0.43187061,
        -0.4318706 , -0.33721865, -0.33721865],
       [ 0.6629057 , -0.3370943 ,  0.56822648,  0.56822649, -0.43187061,
        -0.4318706 , -0.33721865, -0.33721865],
       [ 0.56822648,  0.56822648, -0.55304517,  0.44695485, -0.55316953,
         0.44683049, -0.4319328 , -0.4319328 ],
       [ 0.56822649,  0.56822649,  0.44695485, -0.55304513,  0.44683049,
        -0.55316949, -0.43193278, -0.43193278],
       [-0.43187061, -0.43187061, -0.55316953,  0.44683049, -0.55329392,
         0.4467061 ,  0.56797007,  0.56797007],
       [-0.4318706 , -0.4318706 ,  0.44683049, -0.55316949,  0.4467061 ,
        -0.55329388,  0.56797009,  0.56797009],
       [-0.33721865, -0.33721865, -0.4319328 , -0.43193278,  0.56797007,
         0.56797009, -0.33734305,  0.66265695],
       [-0.33721865, -0.33721865, -0.4319328 , -0.43193278,  0.56797007,
         0.56797009,  0.66265695, -0.33734305]])

In [10]:
metpot2(A_ejemplo)

(array([ 0.39418325,  0.39418325,  0.30785101,  0.3077675 , -0.30756118,
        -0.30764469, -0.39402216, -0.39402216]),
 2.5615528302797395,
 True)

In [15]:
metpotI(A_ejemplo, 0.01)

(array([-2.83931205e-08, -2.61103567e-08,  5.00000021e-01, -4.99999978e-01,
        -4.99999979e-01,  5.00000021e-01, -3.27205352e-08, -2.09852090e-08]),
 -0.0200000000000026,
 True)

In [16]:
metpotI2(A_ejemplo, 0.01)

(array([-6.87650612e-06, -7.69625874e-06,  5.00006019e-01, -4.99994284e-01,
        -4.99994279e-01,  5.00005418e-01, -8.87102568e-06, -5.30134679e-06]),
 -50.01000160264857,
 True)