# Segunda parte del TP de ALC 2025

In [1]:
# Carga de paquetes necesarios para graficar
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd # Para leer archivos
import geopandas as gpd # Para hacer cosas geográficas
import seaborn as sns # Para hacer plots lindos
import networkx as nx # Construcción de la red en NetworkX
import scipy

##### Carga de funciones del Template

In [2]:
# Importamos las funciones del template
from template_funciones_2 import *

In [3]:
s = (1,1,1,-8,-2,2,-2,2)

vector_s(s)

array([ 1.,  1.,  1., -1., -1.,  1., -1.,  1.])

# Pruebas con la matriz base

In [4]:
# Matriz A de ejemplo
A_ejemplo = np.array([
    [0, 1, 1, 1, 0, 0, 0, 0],
    [1, 0, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 1],
    [0, 0, 1, 0, 1, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 0, 1],
    [0, 0, 0, 0, 1, 1, 1, 0]
])

A_ejemplo

array([[0, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0]])

In [5]:
calcular_matriz_K(A_ejemplo)

array([[3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 3.]])

In [6]:
np.linalg.eigvals(A_ejemplo)[np.argsort(np.abs(np.linalg.eigvals(A_ejemplo)))]

array([ 2.05561087e-17, -5.61552813e-01, -1.00000000e+00, -1.00000000e+00,
       -1.56155281e+00, -2.00000000e+00,  2.56155281e+00,  3.56155281e+00])

In [7]:
np.linalg.eig(A_ejemplo)[1][np.argsort(np.abs(np.linalg.eigvals(A_ejemplo)))]

array([[-3.07706105e-01,  3.94102719e-01, -3.07706105e-01,
         8.26507924e-17,  3.94102719e-01, -3.44500665e-16,
         2.91167878e-17, -7.06603681e-01],
       [-3.94102719e-01,  3.07706105e-01,  3.94102719e-01,
        -1.35752217e-16, -3.07706105e-01, -5.00000000e-01,
         5.00000000e-01,  2.43540988e-18],
       [-3.94102719e-01, -3.07706105e-01, -3.94102719e-01,
        -1.00809392e-16, -3.07706105e-01,  5.00000000e-01,
         5.00000000e-01,  2.32474286e-16],
       [-3.07706105e-01,  3.94102719e-01, -3.07706105e-01,
         8.26507924e-17,  3.94102719e-01, -3.26989267e-16,
         1.38749368e-16,  7.06603681e-01],
       [-3.94102719e-01, -3.07706105e-01, -3.94102719e-01,
         8.82754672e-17, -3.07706105e-01, -5.00000000e-01,
        -5.00000000e-01, -1.54176994e-16],
       [-3.94102719e-01,  3.07706105e-01,  3.94102719e-01,
        -2.99340848e-17, -3.07706105e-01,  5.00000000e-01,
        -5.00000000e-01, -3.17167278e-17],
       [-3.07706105e-01, -3.941027

In [8]:
metpot1(A_ejemplo)

(array([0.30776336, 0.30776336, 0.39414743, 0.39414742, 0.39405801,
        0.394058  , 0.30764884, 0.30764884]),
 3.561552791699327,
 True)

In [9]:
deflaciona(A_ejemplo)

array([[-0.33707616,  0.66292384,  0.56824434,  0.56824591, -0.43186679,
        -0.43186522, -0.33721865, -0.33721865],
       [ 0.66292384, -0.33707616,  0.56824434,  0.56824591, -0.43186679,
        -0.43186522, -0.33721865, -0.33721865],
       [ 0.56824434,  0.56824434, -0.55302917,  0.44697284, -0.55317151,
         0.4468305 , -0.43193817, -0.43193817],
       [ 0.56824591,  0.56824591,  0.44697284, -0.55302515,  0.4468305 ,
        -0.55316749, -0.4319366 , -0.4319366 ],
       [-0.43186679, -0.43186679, -0.55317151,  0.4468305 , -0.55331389,
         0.44668812,  0.56795066,  0.56795066],
       [-0.43186522, -0.43186522,  0.4468305 , -0.55316749,  0.44668812,
        -0.55330988,  0.56795223,  0.56795223],
       [-0.33721865, -0.33721865, -0.43193817, -0.4319366 ,  0.56795066,
         0.56795223, -0.33736119,  0.66263881],
       [-0.33721865, -0.33721865, -0.43193817, -0.4319366 ,  0.56795066,
         0.56795223,  0.66263881, -0.33736119]])

In [12]:
metpot2(A_ejemplo,0.5)

(array([-0.51592246, -0.53979216, -0.36494215, -0.44832878,  0.05667318,
        -0.02671345,  0.25515366,  0.19808615]),
 2.625628510043462,
 True)