# Segunda parte del TP de ALC 2025

In [1]:
# Carga de paquetes necesarios para graficar
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd # Para leer archivos
import geopandas as gpd # Para hacer cosas geográficas
import seaborn as sns # Para hacer plots lindos
import networkx as nx # Construcción de la red en NetworkX
import scipy

##### Carga de funciones del Template

In [2]:
# Importamos las funciones del template
from template_funciones_2 import *

# Pruebas con la matriz base

In [3]:
# Matriz A de ejemplo
A_ejemplo = np.array([
    [0, 1, 1, 1, 0, 0, 0, 0],
    [1, 0, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 1],
    [0, 0, 1, 0, 1, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 0, 1],
    [0, 0, 0, 0, 1, 1, 1, 0]
])

A_ejemplo

array([[0, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0]])

In [4]:
info = np.linalg.eig(A_ejemplo)

print("Autovalores: " + str(info[0]))
print("Autovectores:")
print(info[1])

Autovalores: [ 3.56155281e+00  2.56155281e+00 -1.56155281e+00 -1.00000000e+00
 -5.61552813e-01 -2.00000000e+00  2.05561087e-17 -1.00000000e+00]
Autovectores:
[[-3.07706105e-01 -3.94102719e-01  3.07706105e-01  7.07106781e-01
   3.94102719e-01  1.33395986e-16  4.36856353e-17 -2.66690374e-02]
 [-3.07706105e-01 -3.94102719e-01  3.07706105e-01 -7.07106781e-01
   3.94102719e-01  2.33555879e-16 -1.96406098e-16  2.66690374e-02]
 [-3.94102719e-01 -3.07706105e-01 -3.94102719e-01  8.82754672e-17
  -3.07706105e-01 -5.00000000e-01 -5.00000000e-01 -1.54176994e-16]
 [-3.94102719e-01 -3.07706105e-01 -3.94102719e-01 -1.00809392e-16
  -3.07706105e-01  5.00000000e-01  5.00000000e-01  2.32474286e-16]
 [-3.94102719e-01  3.07706105e-01  3.94102719e-01 -1.35752217e-16
  -3.07706105e-01 -5.00000000e-01  5.00000000e-01  2.43540988e-18]
 [-3.94102719e-01  3.07706105e-01  3.94102719e-01 -2.99340848e-17
  -3.07706105e-01  5.00000000e-01 -5.00000000e-01 -3.17167278e-17]
 [-3.07706105e-01  3.94102719e-01 -3.0770610

In [5]:
metpotI(A_ejemplo, 0.0001)

(array([-7.73266778e-13, -7.83859269e-13, -5.00000000e-01,  5.00000000e-01,
         5.00000000e-01, -5.00000000e-01,  5.63940252e-13, -2.02438477e-12]),
 -0.00019999999964629195,
 True)

In [6]:
metpotI2(A_ejemplo, 0.01)

(array([-1.58927779e-05, -1.60069086e-05,  5.00014847e-01, -4.99985654e-01,
        -4.99985577e-01,  5.00013921e-01, -1.97063239e-05, -1.22893182e-05]),
 -50.01000871272106,
 True)

In [7]:
modularidad_iterativo(A_ejemplo)

Primera R:
[[-0.32142857  0.67857143  0.57142857  0.57142857 -0.42857143 -0.42857143
  -0.32142857 -0.32142857]
 [ 0.67857143 -0.32142857  0.57142857  0.57142857 -0.42857143 -0.42857143
  -0.32142857 -0.32142857]
 [ 0.57142857  0.57142857 -0.57142857  0.42857143 -0.57142857  0.42857143
  -0.42857143 -0.42857143]
 [ 0.57142857  0.57142857  0.42857143 -0.57142857  0.42857143 -0.57142857
  -0.42857143 -0.42857143]
 [-0.42857143 -0.42857143 -0.57142857  0.42857143 -0.57142857  0.42857143
   0.57142857  0.57142857]
 [-0.42857143 -0.42857143  0.42857143 -0.57142857  0.42857143 -0.57142857
   0.57142857  0.57142857]
 [-0.32142857 -0.32142857 -0.42857143 -0.42857143  0.57142857  0.57142857
  -0.32142857  0.67857143]
 [-0.32142857 -0.32142857 -0.42857143 -0.42857143  0.57142857  0.57142857
   0.67857143 -0.32142857]]
autoval: [ 2.56155281e+00 -1.56155281e+00 -1.40079839e-16 -1.00000000e+00
 -5.71428571e-01 -2.00000000e+00  4.16333634e-17 -1.00000000e+00]
autovectores
[[-3.94102719e-01 -3.077061

TypeError: list indices must be integers or slices, not tuple

In [ ]:
def draw_graph_with_communities(A, communities):
    G = nx.from_numpy_array(A)

    # Assign a unique color to each community
    colors = plt.cm.get_cmap('tab10', len(communities))
    node_colors = [None] * len(A)

    for i, group in enumerate(communities):
        for node in group:
            node_colors[node] = colors(i)

    pos = nx.spring_layout(G, seed=42)
    nx.draw(G, pos, node_color=node_colors, with_labels=True, edge_color='gray')
    plt.show()
    
#draw_graph_with_communities(A_ejemplo, modularidad_iterativo(A_ejemplo))

In [ ]:
def random_symmetric_adjacency(n=12, p=0.3, seed=None):
    if seed is not None:
        np.random.seed(seed)

    A = np.triu((np.random.rand(n, n) < p).astype(int), 1)
    A = A + A.T  # make symmetric
    return A

A = random_symmetric_adjacency(12, p=0.3)

#modularidad_iterativo(A)

In [ ]:
#draw_graph_with_communities(A, modularidad_iterativo(A))